### ISSUE TITLE
OS X FF support

### ISSUE THREAD

**Issue by Diokuz** [Diokuz/baron#110]
Baron cant support that browser, because

https://bugzilla.mozilla.org/show_bug.cgi?id=926294

Some thoughts how to support it anyway:

1. Make padding-right: +10px and delta +10px. Was blocked by this bug https://bugzilla.mozilla.org/show_bug.cgi?id=157846 need to verify it.
2. ~~Hide scrollbar by z-index > 0~~ bug that makes it possible was fixed https://bugzilla.mozilla.org/show_bug.cgi?id=891136

**Comment by Diokuz** [comment]
Its time to do something here.

https://github.com/Diokuz/baron/issues/91

**Comment by Diokuz** [comment]
https://github.com/Diokuz/baron/commit/aa739717f34a320713b2be0767a55b3e7ce9e724

**Comment by Diokuz** [comment]
Need to verify textarea.

**Comment by Diokuz** [comment]
Textarea is good.

**Comment by andreyvolokitin** [comment]
I think there might be a problem with determining content dimensions (particularly, height) in OS X FF.  I.e., for horizontal direction, the native scrollbar is located in the 15px padding area, but the content heigh itself is still 15px larger than actually needed (on top of additional 15px padding). Because of that, overall height set by baron is larger by 15px in OS X FF. It sets height substracting 15px padding from content height, but content height itself is larger by 15px, so it appears that it would be optimal to actually substract double 15px...

I might investigate further providing a proper test-case, but would appreciate a comment if this indeed might be possible, or I just did something wrong
