### ISSUE TITLE
Firefox 31 (ESR) bug

### ISSUE THREAD

**Issue by brunowego** [Diokuz/baron#91]
Please take a look in this bug on Firefox 31:

![error](https://cloud.githubusercontent.com/assets/441774/9645387/aa052588-51a1-11e5-98d9-20f187e4f63e.gif)

Have any idea how solve it? Thanks.

**Comment by clexit** [comment]
It happens on Mac OS. I think the maintainer said that they sniff for FF on Mac and don't initialize baron there, since native scrollbars look OK anyway (hope he will correct me if I'm wrong).

>> Have any idea how solve it?
A bit hacky way would be to add something like "margin-right: -30px; padding-right: 30px;" to a scrollable container and then cut these 30px by setting "overflow: hidden" to a wrapper, so the native scrollbars will be hidden.

**Comment by brunowego** [comment]
Thanks @clexit :+1:

**Comment by antelle** [comment]
If Firefox under Mac is not supported (as stated in #93), I suggest adding it to readme with link to this issue and especially [this](https://github.com/Diokuz/baron/issues/91#issuecomment-137350806) comment. And maybe an optional flag to modify padding (or may be enabled by default if cssGuru is off, for example).

**Comment by Diokuz** [comment]
Readme was updated.
But I will try to support Mac FF in #110.
